export const aiTypeMap = {
  market: "分析AI",
  competitor: "分析AI",
  account: "分析AI",
  insight: "分析AI",
  improvement: "AIコンサルティング",
  "improvement-no-image": "AIコンサルティング",
  writing: "ライティングAI（Instagram）",
  "writing-no-image": "ライティングAI（Instagram）",
  "feed-post": "ライティングAI（Instagram）",
  "reel-and-stories": "ライティングAI（Instagram）",
  profile: "ライティングAI（Instagram）",
  "google-map": "ライティングAI（Google Map）",
  "google-map-no-image": "ライティングAI（Google Map）",
  threads: "ライティングAI（Threads）",
  "threads-no-image": "ライティングAI（Threads）",
  "seo-article": "SEO・AIO記事",
} as const;
