name = "insiteai-api"
compatibility_date = "2024-07-30"
main = "src/index.ts"

[vars]
ADMIN_USERNAME = "admin"
ADMIN_PASSWORD = "password"
META_APP_ID = ""
META_APP_SECRET = ""
META_REDIRECT_URI = "http://localhost:8787/api/meta/callback"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "insiteai"

[[d1_databases]]
binding = "DB"
database_name = "database"
database_id = "88fa7318-dd4a-4812-926e-3d718351c52d"

[env.preview.vars]
META_APP_ID = "1701350637561455"
META_REDIRECT_URI = "https://insiteai-api-preview.nakata-haruka.workers.dev/meta/callback"
META_CONFIG_ID = "2495168324281887"
META_CALLBACK_FRONTEND_URL = "https://stg.insiteai-web.pages.dev"
INSTAGRAM_APP_ID = "1065352859485474"
INSTAGRAM_REDIRECT_URI = "https://insiteai-api-preview.nakata-haruka.workers.dev/instagram/callback"
INSTAGRAM_CALLBACK_FRONTEND_URL = "https://stg.insiteai-web.pages.dev"

[[env.preview.r2_buckets]]
binding = "BUCKET"
bucket_name = "insiteai"

[[env.preview.d1_databases]]
binding = "DB"
database_name = "database"
database_id = "08086678-d2c3-4c24-8657-16a51d0a204b"
